config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  root 'friends#index'
  get 'home/about'
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]
  before_action :correct_user, only: %i[ edit update destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "not authorised to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:First_name, :Last_name, :Email, :Twitter, :Phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def about
   
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :First_name, class: "form-control", placeholder: "Firstname" %>
  </div>
<br>
  <div class="field form-group">
    <% form.label :Last_name, style: "display: block" %>
    <%= form.text_field :Last_name, class: "form-control", placeholder: "Last name" %>
  </div>
<br>
  <div class="field form-group">
    <% form.label :Email, style: "display: block" %>
    <%= form.text_field :Email, class: "form-control", placeholder:"Email" %>
  </div>
<br>
  <div class="field form-group">
    <% form.label :Twitter, style: "display: block" %>
    <%= form.text_field :Twitter, class: "form-control", placeholder: "Twitter" %>
  </div>
<br>
  <div class="field form-group">
    <% form.label :Phone, style: "display: block" %>
    <%= form.text_field :Phone, class: "form-control", placeholder: "Phone" %>
  </div>
  <br>
  <div class="field form-group">
    <% form.label :Phone, style: "display: block" %>
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value:current_user.id, type: :hidden %>
  </div>
<br>
  <div>
    <%= form.submit%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<% if friend.user == current_user %>
  <div class="friend-card" id="<%= dom_id friend %>">
    <div class="friend-card-content">
      <p>
        <strong>Name:</strong>
        <%= link_to friend.First_name + ' ' + friend.Last_name, friend %>
      </p>
      <p>
        <strong>Email:</strong>
        <%= friend.Email %>
      </p>
      <p>
        <strong>Twitter:</strong>
        <%= friend.Twitter %>
      </p>
      <p>
        <strong>Phone:</strong>
        <%= friend.Phone %>
      </p>
    </div>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend, class: "btn btn-outline-primary" %> |
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
  <%= button_to "Destroy this friend", @friend, method: :delete, data: { turbo_confirm: 'Are you Sure'}, class: "btn btn-outline-danger" %>
</div>

app/views/friends/index.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %>
<h1>Friend List</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    
    
  <% end %>
</div>

<%= link_to "New friend", new_friend_path, class: "btn btn-secondary"%>
<% else %>
<h1> BUDDY PAGE </h1>

<img src="https://michiganross.umich.edu/sites/default/files/images/news-story/connection2.jpg">
<% end %>

app/views/friends/new.html.erb
<h1> Add New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-secondary" %>
</div>

app/views/friends/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @friend %>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-primary" %>
  <br><br>
  
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-primary" %>
  <br><br>
  <%= button_to "Destroy this friend", @friend, method: :delete, data: { turbo_confirm: 'Are you Sure'}, class: "btn btn-danger" %>
  
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Buddy Page', root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'About Us', '#', class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<p style="color: green"><%= notice %></p>
<% if user_signed_in? %>
<h1>Friend List</h1>

<div id="friends">
  <% @friends.each do |friend| %>
    <%= render friend %>
    
    
  <% end %>
</div>

<%= link_to "New friend", new_friend_path, class: "btn btn-secondary"%>
<% else %>
<h1> BUDDY PAGE </h1>

<img src="https://michiganross.umich.edu/sites/default/files/images/news-story/connection2.jpg">
<% end %>

app/views/home/index.html.erb
<h1> Meet My Buddies </h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong> You should check in on some of those fields below.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ruby On Rails</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <br>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>